# Copyright (c) YugaByte, Inc.

asia-east1:
  name: Taiwan
  latitude: 23.9919519
  longitude: 120.3300829
asia-east2:
  name: Hong Kong
  latitude: 22.319304
  longitude: 114.169361
asia-southeast1:
  name: Singapore
  latitude: 1.352083
  longitude: 103.819836
asia-southeast2:
  name: Jakarta
  latitude: -6.208763
  longitude: 106.845599
asia-northeast1:
  name: Tokyo
  latitude: 35.689488
  longitude: 139.691706
asia-northeast2:
  name: Osaka
  latitude: 34.693725
  longitude: 135.502254
asia-northeast3:
  name: Seoul
  latitude: 37.566535
  longitude: 126.977969
asia-south1:
  name: Mumbai
  latitude: 19.0825223
  longitude: 72.7411014
asia-south2:
  name: Delhi
  latitude: 28.704059
  longitude: 77.10249
us-central1:
  name: Iowa
  latitude: 41.2326957
  longitude: -95.9167207
us-west1:
  name: Oregon
  latitude: 45.6094756
  longitude: -121.2088799
us-west2:
  name: California
  latitude: 34.052235
  longitude: -118.243683
us-west3:
  name: Utah
  latitude: 40.7608
  longitude: -111.8910
us-west4:
  name: Nevada
  latitude: 36.1699
  longitude: -115.1398
us-east1:
  name: South Carolina
  latitude: 33.1637261
  longitude: -80.1845003
us-east4:
  name: Northern Virginia
  latitude: 39.0300218
  longitude: -77.5121424
northamerica-northeast1:
  name: Montreal
  latitude: 45.5581968
  longitude: -73.8703852
northamerica-northeast2:
  name: Toronto
  latitude: 43.653226
  longitude: -79.383184
southamerica-east1:
  name: Sao Paulo
  latitude: -23.286926
  longitude: -46.627497
europe-central2:
  name: Poland
  latitude: 52.229676
  longitude: 21.012229
europe-west1:
  name: Belgium
  latitude: 50.489824
  longitude: 3.7378805
europe-west2:
  name: London
  latitude: 51.500152
  longitude: -0.126236
europe-west3:
  name: Frankfurt
  latitude: 50.111512
  longitude: 8.680506
europe-west4:
  name: Netherlands
  latitude: 53.4356948
  longitude: 6.7980783
europe-west6:
  name: Switzerland
  latitude: 47.376887
  longitude: 8.541694
europe-north1:
  name: Finland
  latitude: 60.5695912
  longitude: 27.2097431
australia-southeast1:
  name: Sydney
  latitude: -33.867139
  longitude: 151.207114
australia-southeast2:
  name: Melbourne
  latitude:  -37.813628
  longitude: 144.963058
