# Copyright 2022 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
  - name: Install cgconfig service on CentOS
    package:
      name:
        - libcgroup
        - libcgroup-tools
      state: present
    register: result
    until: result is succeeded
    retries: "{{ install_retry_count }}"

  - name: Add ysql cgroup info to cgconfig.conf
    template:
      src: cgconfig.conf.j2
      dest: "/etc/cgconfig.conf"
      mode: 0755

  - name: Start cgconfig service
    ansible.builtin.service:
      name: cgconfig
      state: restarted

  - name: Enable cgconfig service
    ansible.builtin.service:
      name: cgconfig
      enabled: yes
  when: ansible_os_family == 'RedHat' and not air_gap and pg_max_mem_mb > 0
