blank_issues_enabled: false
contact_links:
  - name: Cloud
    about: Create a Cloud issue.
    url: https://support.yugabyte.com/hc/en-us/requests/new?ticket_form_id=360003113431
  - name: Platform
    about: Create a Platform issue.
    url: https://support.yugabyte.com/hc/en-us/requests/new?ticket_form_id=360001955891
